**SET**

In [8]:
fruits = {'apple', 'banana', 'apple', 'orange'}


In [9]:
print(type(fruits))

<class 'set'>


In [10]:
# Another way of using or defining a set using 'set' construct
vegetables = set([1, 2, 2, 3])
print(vegetables)

{1, 2, 3}


In [11]:
empty_set = set()
print(empty_set)

set()


In [14]:
# Creating an empty dictionary
dict1 = {}
print(type(dict1))

<class 'dict'>


In [18]:
set1 = set()
print(type(set1))

<class 'set'>


In [20]:
# Adding element in set
set1.add(1)
set1

{1}

In [27]:
# updating the elements
set1.update([2, 3])
set1.update([2, 3, 5]) # repeating elements do not get added
print(set1)

{1, 2, 3, 5}


In [28]:
# removing elements
set1.remove(5)
set1

{1, 2, 3}

In [29]:
set1.discard(3)
set1

{1, 2}

Difference between `.discard()` and `.remove()` is that , even if the element is not present in the set, no error will be shown by `.discard()` while `.remove()` will show an error

In [30]:
set1.pop() 

1

In [31]:
set1.pop()

2

In [32]:
set1

set()

In [33]:
set2 = {1, 16, 4, 8}
set2.pop?

Signature: set2.pop()
Docstring:
Remove and return an arbitrary set element.

Raises KeyError if the set is empty.
Type:      builtin_function_or_method

In [34]:
set.discard?

Signature: set.discard(self, object, /)
Docstring:
Remove an element from a set if it is a member.

Unlike set.remove(), the discard() method does not raise
an exception when an element is missing from the set.
Type:      method_descriptor

In [35]:
# to remove all elements of the set at once.
set2.clear()

In [36]:
set2

set()

In [40]:
set1 = {1, 2, 3, 6, 7}
set2 = {3, 4, 5, 6, 12}
set3 = set1.union(set2)
set3

{1, 2, 3, 4, 5, 6, 7, 12}

In [43]:
set4 = set1.intersection(set2)
set4

{3, 6}

In [48]:
print(set1.difference(set2))
print(set2.difference(set1))

{1, 2, 7}
{12, 4, 5}


Write a program to create a set having nos 1 to 10 and another set having 2 to 20 and perform union, difference and intersection and also add elements using update.

In [52]:
set1 = set()
set2 = set()

set1.update(range(1, 11))
set2.update(range(2, 21))

print("Set 1 :- ", set1)
print("Set 2 :- ", set2)

setU = set1.union(set2)
setI = set1.intersection(set2)
setD1 = set1.difference(set2)
setD2 = set2.difference(set1)

print("Union = ", setU)
print("Intersection = ", setI)
print("Difference set1 - set2 = ", setD1)
print("Difference set2 - set1 = ", setD2)

Set 1 :-  {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
Set 2 :-  {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20}
Union =  {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20}
Intersection =  {2, 3, 4, 5, 6, 7, 8, 9, 10}
Difference set1 - set2 =  {1}
Difference set2 - set1 =  {11, 12, 13, 14, 15, 16, 17, 18, 19, 20}


In [53]:
setA = {1, 2, 3, 4, 5, 6}
setB = {2, 3, 4}
set1.issubset(set2)

False

In [54]:
setA.issuperset(setB)

True

In [55]:
setA.isdisjoint(setB)

False

In [57]:
setC = setA.copy() # Shallow Copy
setC

{1, 2, 3, 4, 5, 6}

In [58]:
set111 = {1, "Hello"}   

**File Handling**

In [65]:
with open("sample.txt", "w") as f:
    f.write("Hello students!\nWelcome to Python file handling,\nLet's learn together.")

In [68]:
with open("sample.txt", "r") as f:
    content = f.read()
    print(content)

Hello students!
Welcome to Python file handling,
Let's learn together.


Modes = 

* read :- r
* write :- w
* append :- a
* create :- x

In [70]:
with open("sample.txt", "a") as f:
    f.write("\nThis lines is added later.")

In [71]:
with open("sample.txt", "r") as file:
    for i in file:
        print(i.strip())

Hello students!
Welcome to Python file handling,
Let's learn together.
This lines is added later.


**WAP to read a file and count the words in it.**

In [80]:
def count_words(filename):
    with open(filename, "r") as file:
        text = file.read().lower()
        for ch in ['.', '?', ',', '!', ';', ':']:
            text = text.replace(ch, '')
        words = text.split()
        return len(words)

with open("smple2", "w") as mi:
    mi.write("Python is a really cool language.\nThe code is crisp and precise.\nFile handling is real easy with Python.\nI really enjoy coding with Python.\nlearn Python.")

with open("smple2", "a") as ml:
    ml.write("Learning Python is essential to learn Data Science and Machine Learning.\nCreating, Reading and Writing files is really use.\nIt is really interesting")

print("Number of words in the file: ", count_words("smple2"))

Number of words in the file:  49


In [73]:
import json

student = { "name": "priya", "age": 24, "marks": [85, 90, 88]}

with open("student.json", "w") as f:
    json.dump(student, f)

In [74]:
with open("student.json", "r") as f:
    data = json.load(f)
    print(data)

{'name': 'priya', 'age': 24, 'marks': [85, 90, 88]}


In [77]:
import os

if not os.path.exists("my_folder"):
    os.mkdir("my_folder")

files = os.listdir(".")
print("Files in current directory:", files)

Files in current directory: ['.idea', '.ipynb_checkpoints', 'Advanced Machine Learning.ipynb', 'Advertising.csv', 'bank.csv', 'beer.csv', 'BEML.csv', 'Binary Tree.py', 'BST.py', 'CDAC Classes.ipynb', 'CDAC HW1.ipynb', 'chd1_tree.odt', 'chd_tree.odt', 'chd_tree.png', 'chd_tree1.odt', 'chd_tree1.png', 'chd_tree5.odt', 'chd_tree5.png', 'chd_tree_entropy.odt', 'chd_tree_entropy.png', 'Classification.ipynb', 'Clustering.ipynb', 'country.csv', 'curve.csv', 'customerspends.csv', 'CustomerSpends.ipynb', 'DynamicProgramming.py', 'Earnings Manipulation 220.csv', 'Earnings Manipulation Classification.ipynb', 'fifa_data.csv', 'forecast.xls', 'Forecasting.ipynb', 'ForecastingExercises.ipynb', 'Gain and Lift Chart.ipynb', 'gas_prices.csv', 'German Credit Data.csv', 'GLAXO.csv', 'Graphs.py', 'groceries.csv', 'HashTable.py', 'HR_Data Classification and DT.ipynb', 'hr_data.csv', 'Income Data.csv', 'IPL IMB381IPL2013.csv', 'LEarningMatplotlib.ipynb', 'LinearRegression.ipynb', 'matplot.py', 'MBA Salary.c

In [79]:
os.rename("sample.txt", "sample4.txt")

**Merge contents of 2 text files and show in a new file**

In [86]:
content1 = ""
content2 = ""

with open("sample4.txt", "r") as f1:
    content1 = f1.read()

with open("smple2", "r") as f2:
    content2 = f2.read()

with open("New Merged File.txt", "w") as nf:
    nf.write(content1)

with open("New Merged File.txt", "a") as nf2:
    nf2.write(content2)

with open("New Merged File.txt", "r") as nf3:
    text = nf3.read()
    print(text)

Hello students!
Welcome to Python file handling,
Let's learn together.
This lines is added later.Python is a really cool language.
The code is crisp and precise.
File handling is real easy with Python.
I really enjoy coding with Python.
learn Python.Learning Python is essential to learn Data Science and Machine Learning.
Creating, Reading and Writing files is really use.
It is really interesting


**Exception Handling**

In [ ]:
try:
    num1 = int(input("Enter a number: "))
    num2 = int(input("Enter another number: "))
    print(num1/num2)
except ZeroDivisionError:
    print("Cannot divide by zero!")
except ValueError:
    print("invalid Input. Please enter a valid number.")

**WAP to handle errors like not a string.**

In [83]:
try:
    age = int(input("Enter a number: "))
    if age < 0:
        raise ValueError("Age cannot be negative")
except ValueError as e:
    print(e)

Enter a number:  -9


Age cannot be negative


In [87]:
with open("binary_file.bin", "wb") as f:
    f.write(b"This is binary content\n 1234")

with open("binary_file.bin", "rb") as f:
    content = f.read()
    print(content)

b'This is binary content\n 1234'


**NumPy**

In [1]:
import numpy as np


In [3]:
l2 = np.array([1, 6, 3, 4])
type(l2)

numpy.ndarray

In [4]:
print(l2 * 5)

[ 5 30 15 20]


In [5]:
# We can store heterogeneous data type
l3 = np.array([1, 2, 3, "hello"])

In [6]:
l2[2] = 25
l2

array([ 1,  6, 25,  4])

In [13]:
l4 = np.array([[1, 2, 3, 7, 8], 
               [4, 5, 6, 4, 5], 
               [7, 8, 9, 3, 4]])
l4.ndim # Gives the dimension of the array

2

In [14]:
l4.shape

(3, 5)

In [16]:
print(l4.dtype)

int64


In [17]:
l4.size

15

In [18]:
l5 = np.array([1, 2, 3, 4, 5])

In [22]:
print(l4[1, 4])

5


In [23]:
print(l4[:2])

[[1 2 3 7 8]
 [4 5 6 4 5]]


In [27]:
l5 = np.array([[1, 2, 3, 7, 8], 
               [4, 5, 6, 6, 5], 
               [7, 8, 9, 3, 4]], dtype='int64')

In [28]:
l5.dtype

dtype('int64')

In [30]:
ar1 = np.array([[1, 2, 3, 5, 6, 7, 8],
               [5, 4, 6, 8, 3, 3, 2],
               [6, 5, 4, 7, 2, 4, 3],
               [4, 5, 2, 8, 6, 4, 3],
               [5, 9, 4, 2, 3, 5, 9]])
print(ar1.size)
print(ar1.dtype)
print(ar1.shape)
print(ar1[4, 6])

35
int64
(5, 7)
9


In [32]:
d = {'1' : 'A'}
l7 = np.array([[1, 2, 3], [4, d, 6], [7, 8, 'hello']])
print(l7.dtype)

object


In [34]:
l9 = np.zeros((5, 5, 2))
l9

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [37]:
l9 = np.ones((2, 5, 1), dtype='int32')

In [38]:
l9

array([[[1],
        [1],
        [1],
        [1],
        [1]],

       [[1],
        [1],
        [1],
        [1],
        [1]]], dtype=int32)

In [40]:
l12 = np.arange(0, 10, 3)
l12

array([0, 3, 6, 9])

In [42]:
l13 = np.linspace(0, 100)
l13

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [44]:
l14 = np.linspace(0, 100, 5)
l14

array([  0.,  25.,  50.,  75., 100.])

In [47]:
l15 = np.linspace(1, 100, 2)
l15

array([  1., 100.])

In [48]:
l13 = [1,4,9,16]
print(np.sqrt(l13))

[1. 2. 3. 4.]


In [49]:
l14 = np.full((2, 3, 4), 9)
l14

array([[[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]]])

In [51]:
import time

a_list = list(range(1000000))
start = time.time()
a_list = [x + 1 for x in a_list]
end = time.time()
print("Time with List : ", end - start)

b_arr = np.array(range(1000000))
start = time.time()
b_arr = b_arr + 1
end = time.time()
print("Time with NumPy: ", end - start)

Time with List :  0.23472332954406738
Time with NumPy:  0.021486282348632812


In [52]:
l15 = [1, 2, 3, 4, 5]
l16 = [6, 7, 8, 9, 10]
a1 = np.array(l15)
a2 = np.array(l16)

In [53]:
print(l15 + l16) # Concatenating

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [55]:
print(a1 + a2) # Adding the elements

[ 7  9 11 13 15]


In [56]:
print(a1 * a2)

[ 6 14 24 36 50]


In [58]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([[1], [2], [3]])
print(a1 + a2)

[[2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


In [59]:
print(np.sqrt(a1))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [60]:
a2 = [7, 8, 9]
a = np.append(a1, a2)
print(a)

[1 2 3 4 5 7 8 9]


In [62]:
a3 = np.insert(a, 3, [8, 9, 10])
a3

array([ 1,  2,  3,  8,  9, 10,  4,  5,  7,  8,  9])

In [63]:
a4 = np.delete(a3, 1)
a4

array([ 1,  3,  8,  9, 10,  4,  5,  7,  8,  9])

In [65]:
a5 = np.sort(a4)
a5

array([ 1,  3,  4,  5,  7,  8,  8,  9,  9, 10])

In [68]:
a4 = np.array([[1, 2, 3, 4, 5],
               [6, 7, 8, 9, 10],
               [11, 12, 13, 14, 15],
               [16, 17, 18, 19, 20]])
a5 = np.delete(a4, 0,1)
a5

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

In [70]:
print(a4.reshape(2, 10))

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [74]:
print(a4.reshape(5, 2, 2))

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]

 [[17 18]
  [19 20]]]


In [77]:
a5 = a4.reshape(20)
print(a4.flatten()) # Converts to 1-D NumPy array

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [78]:
a.reshape?

Docstring:
a.reshape(shape, /, *, order='C', copy=None)

Returns an array containing the same data with a new shape.

Refer to `numpy.reshape` for full documentation.

See Also
--------
numpy.reshape : equivalent function

Notes
-----
Unlike the free function `numpy.reshape`, this method on `ndarray` allows
the elements of the shape parameter to be passed in as separate arguments.
For example, ``a.reshape(10, 11)`` is equivalent to
``a.reshape((10, 11))``.
Type:      builtin_function_or_method

In [79]:
print(a4.ravel())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [80]:
# Take a 3*3 array and reshape to 1-D
a6 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
a7 = a6.reshape(9)
print(a7)

[1 2 3 4 5 6 7 8 9]


In [84]:
a6 = np.array([[1, 2], [3, 4]])
b1 = a6.flatten() # Shallow COpy
b1[0] = 50
print(a6)

[[1 2]
 [3 4]]


In [83]:
a6 = np.array([[1, 2], [3, 4]])
b1 = a6.ravel() # Deep Copy
b1[0] = 50
print(a6)

[[50  2]
 [ 3  4]]


In [87]:
a6 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
print(a6.T) # Transpose

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [89]:
m1 = np.random.randint(100)
m2 = int(input("Enter a number: "))
if m1 == m2:
    print("You won!!")
else:
    print("You lose!!")
    print(m1)

Enter a number:  69


You won!!


In [90]:
numbers = np.random.choice([10, 20, 30, 40, 50])
print(numbers)

20


In [91]:
np.save("myarray.npy", a4)

In [92]:
np.savetxt("myarray.csv", a4, delimiter=",")

Make an array of big dimensions and import it and export it.

In [94]:
ar20 = np.array([list(range(1, 1001)), list(range(1000, 2000)), list(range(2000, 3000))])

In [96]:
np.savetxt("largearray.csv", ar20, delimiter=",")

In [97]:
a = np.loadtxt("largearray.csv", delimiter=",")

Assignment 

1. Split 4 cross 4 cross 4 array into 4,  2 cross 2 arrays.
2. Stack two vertical arrays (columns only). Calculate row wise and column wise of the matrix.
3. Create a 3 by 3 array with Default Value=7

**Regular Expressions**

In [100]:
import re
text = "My name is Soubhik"
result = re.search("Soubhik", text)
if result:
    print("Found")
else:
    print("not Found")
result

Found


<re.Match object; span=(11, 18), match='Soubhik'>

In [101]:
result2 = re.match("My", text) # Searches whether test starts with "My" or not
result2

<re.Match object; span=(0, 2), match='My'>

In [102]:
re.search("S..bhik", text)

<re.Match object; span=(11, 18), match='Soubhik'>

In [106]:
re.search("^My", text)

<re.Match object; span=(0, 2), match='My'>

In [105]:
re.search("Soubhik$", text) # If the string ends with that

<re.Match object; span=(11, 18), match='Soubhik'>

In [110]:
re.search("[aeiou]", "elephant") # [aeiou] is char set, matches the first occurrence

<re.Match object; span=(0, 1), match='e'>

In [111]:
re.search("go*d", "gd") # * means 0 or more times

<re.Match object; span=(0, 2), match='gd'>

In [113]:
re.search("go+d", "god") # + ---> 1 or more times checks only the character before the symbol

<re.Match object; span=(0, 3), match='god'>

In [116]:
re.search("go?d", "gd") # ? ---> 0 or 1 times only

<re.Match object; span=(0, 2), match='gd'>

In [117]:
# {} ---> used to match specific number of repetitions
re.search("a{3}", "aaab")

<re.Match object; span=(0, 3), match='aaa'>

In [118]:
re.search("a{2, 5}", "aaaaaab")

In [119]:
text = "Today is 14th June, tomorrow is 15th"
re.findall(r"\d+", text)

['14', '15']

In [120]:
text = "python is easy"
re.sub("easy", "awesome", text)

'python is awesome'

In [121]:
re.split(r"\s", "hello World")

['hello', 'World']

In [129]:
import re

email = "test123@gmail.com"
pattern = r"[a-zA-Z0-9._]+@[a-z]+\.[a-z]{2,}"
print(re.fullmatch(pattern, email))


<re.Match object; span=(0, 17), match='test123@gmail.com'>


In [130]:
# mobile number verification
phone = "9876543210"
pattern = r"[6-9]\d{9}"
re.fullmatch(pattern, phone)

<re.Match object; span=(0, 10), match='9876543210'>

In [133]:
# Password Strength
password = "Hello@123"
pattern = r"(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[@#$])"
re.search(pattern, password)

<re.Match object; span=(0, 0), match=''>

In [1]:
import pandas as pd

In [3]:
data = pd.Series([10, 20, 30, 40, 50], index=['a', 'b', 'c', 'd', 'e'])
print(data)

a    10
b    20
c    30
d    40
e    50
dtype: int64


In [4]:
data['a']

np.int64(10)

In [5]:
print(data[1:2])

b    20
dtype: int64


In [7]:
data['a'] == 10

np.True_

In [10]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([4, 5, 6, 7, 8])
print(s1 * s2)

0     4
1    10
2    18
3    28
4    40
dtype: int64


In [11]:
data = { 
    'a' : 100,
    'b' : 200,
    'c' : 300,
}
s = pd.Series(data)
s

a    100
b    200
c    300
dtype: int64

In [50]:
data = {
    'Name' : ['Amit', 'Riya', 'John', 'Diya', 'Aman'],
    'Age'  : [25, 22, 23, 45, 27],
    'Marks': [85, 90, 78, 90, 87],
    'Sub'  :['Eng', 'Hindi', 'Beng', 'Math', 'Phy']
}
df = pd.DataFrame(data)
df

Name  Age  Marks    Sub
0  Amit   25     85    Eng
1  Riya   22     90  Hindi
2  John   23     78   Beng
3  Diya   45     90   Math
4  Aman   27     87    Phy

In [51]:
print(df.Age)

0    25
1    22
2    23
3    45
4    27
Name: Age, dtype: int64


In [52]:
df['Grade'] = ['B', 'A', 'C', 'A', 'B'] # or do df['Grade'] = 'B' for all rows same value
df

Name  Age  Marks    Sub Grade
0  Amit   25     85    Eng     B
1  Riya   22     90  Hindi     A
2  John   23     78   Beng     C
3  Diya   45     90   Math     A
4  Aman   27     87    Phy     B

In [53]:
df.at[1, "Age"] = 26
df

Name  Age  Marks    Sub Grade
0  Amit   25     85    Eng     B
1  Riya   26     90  Hindi     A
2  John   23     78   Beng     C
3  Diya   45     90   Math     A
4  Aman   27     87    Phy     B

In [54]:
df[df["Marks"] > 80]

Name  Age  Marks    Sub Grade
0  Amit   25     85    Eng     B
1  Riya   26     90  Hindi     A
3  Diya   45     90   Math     A
4  Aman   27     87    Phy     B

In [55]:
df.head(2)

Name  Age  Marks    Sub Grade
0  Amit   25     85    Eng     B
1  Riya   26     90  Hindi     A

In [56]:
df.describe()

Age      Marks
count   5.000000   5.000000
mean   29.200000  86.000000
std     8.955445   4.949747
min    23.000000  78.000000
25%    25.000000  85.000000
50%    26.000000  87.000000
75%    27.000000  90.000000
max    45.000000  90.000000

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    5 non-null      object
 1   Age     5 non-null      int64 
 2   Marks   5 non-null      int64 
 3   Sub     5 non-null      object
 4   Grade   5 non-null      object
dtypes: int64(2), object(3)
memory usage: 332.0+ bytes


In [58]:
df.loc[1]

Name      Riya
Age         26
Marks       90
Sub      Hindi
Grade        A
Name: 1, dtype: object

In [59]:
df.loc[:, 'Age']

0    25
1    26
2    23
3    45
4    27
Name: Age, dtype: int64

In [60]:
df.iloc[1]

Name      Riya
Age         26
Marks       90
Sub      Hindi
Grade        A
Name: 1, dtype: object

In [64]:
df.iloc[1::2, 1]

1    26
3    45
Name: Age, dtype: int64

In [65]:
s = pd.Series([10, 20, 30], index=['A', 'B', 'C'])
df = s.to_frame(name='Marks')
print(df)

   Marks
A     10
B     20
C     30


In [68]:
dis = {
    'a':[1, 2, 3, 4, 5],
    'b':[6, 7, 8, 9, 10],
    'c':[2, 4, 6, 8, 10]
}
df = pd.DataFrame(dis)
df.to_csv('test_1.csv', index=False)

In [77]:
csv_1 = pd.read_csv('Students_Grading_Dataset_Biased.csv', index_col='Student_ID')
# For skipping the rows use skiprows = 1

In [78]:
pd.read_csv?

Signature:
pd.read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    *,
    sep: 'str | None | lib.NoDefault' = <no_default>,
    delimiter: 'str | None | lib.NoDefault' = None,
    header: "int | Sequence[int] | None | Literal['infer']" = 'infer',
    names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>,
    index_col: 'IndexLabel | Literal[False] | None' = None,
    usecols: 'UsecolsArgType' = None,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters: 'Mapping[Hashable, Callable] | None' = None,
    true_values: 'list | None' = None,
    false_values: 'list | None' = None,
    skipinitialspace: 'bool' = False,
    skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None,
    skipfooter: 'int' = 0,
    nrows: 'int | None' = None,
    na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None,
    keep_default_na: 'bool' = True,
    na_filter: '

In [111]:
df1 = pd.DataFrame({
    'Name' : ['Alice', 'Bob', 'Cathy', 'Chandani'],
    'Age' : [25, None, 30, None]
})
df1

Name   Age
0     Alice  25.0
1       Bob   NaN
2     Cathy  30.0
3  Chandani   NaN

In [112]:
df1.isnull().sum()

Name    0
Age     2
dtype: int64

In [110]:
df1.bfill()

Name   Age
0     Alice  25.0
1       Bob  30.0
2     Cathy  30.0
3  Chandani   NaN

In [114]:
df1.isnull().values.any()

np.True_

In [118]:
df1 = pd.DataFrame({'Name':['Alice', 'Bob'], 'Age':[25, 30]})
df2 = pd.DataFrame({'Name':['Cathy', 'David'], 'Age':[22, 28]})
result = pd.concat([df1, df2], ignore_index=True)
result

Name  Age
0  Alice   25
1    Bob   30
2  Cathy   22
3  David   28

In [119]:
result.reset_index?

Signature:
result.reset_index(
    level: 'IndexLabel | None' = None,
    *,
    drop: 'bool' = False,
    inplace: 'bool' = False,
    col_level: 'Hashable' = 0,
    col_fill: 'Hashable' = '',
    allow_duplicates: 'bool | lib.NoDefault' = <no_default>,
    names: 'Hashable | Sequence[Hashable] | None' = None,
) -> 'DataFrame | None'
Docstring:
Reset the index, or a level of it.

Reset the index of the DataFrame, and use the default one instead.
If the DataFrame has a MultiIndex, this method can remove one or more
levels.

Parameters
----------
level : int, str, tuple, or list, default None
    Only remove the given levels from the index. Removes all levels by
    default.
drop : bool, default False
    Do not try to insert index into dataframe columns. This resets
    the index to the default integer index.
inplace : bool, default False
    Whether to modify the DataFrame rather than creating a new one.
col_level : int or str, default 0
    If the columns have multiple levels, determ

In [120]:
df1 = pd.DataFrame({'ID':[1, 2], 'Name':['Cathy', 'David']})
df2 = pd.DataFrame({'ID':[1, 2], 'Marks':[85, 90]})
result = pd.merge(df1, df2, on='ID')
result

ID   Name  Marks
0   1  Cathy     85
1   2  David     90

In [122]:
set1 = set(list(df1.columns))
set2 = set(list(df2.columns))
print("Common Columns = ", set1.intersection(set2))

Common Columns =  {'ID'}


In [124]:
df = pd.DataFrame({
    'Department': ['IT', 'HR', 'IT', 'HR'],
    'Salary' : [60000, 50000, 65000, 52000]
})
grouped = df.groupby('Department').mean()
grouped

Salary
Department         
HR          51000.0
IT          62500.0

In [127]:
data = pd.DataFrame({
    "dept":["IT", 'HR', 'IT', 'HR'],
    'Emp':['A', 'B', 'C', 'D'],
    'Sal':[6000, 7000, 8000, 9000]
})
pivot = data.pivot_table(values='Sal', index='dept', aggfunc='sum')
pivot

Sal
dept       
HR    16000
IT    14000

In [128]:
df = pd.DataFrame({
    'Student':['Alice', 'Bob'],
    'Math':[85, 90],
    'Science':[78, 88]
})
melted = pd.melt(df, id_vars=['Student'], var_name='Subject', value_name='Marks')
melted

Student  Subject  Marks
0   Alice     Math     85
1     Bob     Math     90
2   Alice  Science     78
3     Bob  Science     88

In [129]:
pd.melt?

Signature:
pd.melt(
    frame: 'DataFrame',
    id_vars=None,
    value_vars=None,
    var_name=None,
    value_name: 'Hashable' = 'value',
    col_level=None,
    ignore_index: 'bool' = True,
) -> 'DataFrame'
Docstring:
Unpivot a DataFrame from wide to long format, optionally leaving identifiers set.

This function is useful to massage a DataFrame into a format where one
or more columns are identifier variables (`id_vars`), while all other
columns, considered measured variables (`value_vars`), are "unpivoted" to
the row axis, leaving just two non-identifier columns, 'variable' and
'value'.

Parameters
----------
id_vars : scalar, tuple, list, or ndarray, optional
    Column(s) to use as identifier variables.
value_vars : scalar, tuple, list, or ndarray, optional
    Column(s) to unpivot. If not specified, uses all columns that
    are not set as `id_vars`.
var_name : scalar, default None
    Name to use for the 'variable' column. If None it uses
    ``frame.columns.name`` or 'variable