In [1]:
import numpy as np

**Q1. Split a 4 by 4 array into 4, 2 by 2 arrays.**

In [7]:
arr1 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])
arr1_reshaped = arr1.reshape(4, 2, 2)
a1, a2, a3, a4 = np.array_split(arr1_reshaped, 4)
print("The four split arrays are: ")
print(a1, "\n\n", a2, "\n\n", a3, "\n\n", a4)

The four split arrays are: 
[[[1 2]
  [3 4]]] 

 [[[5 6]
  [7 8]]] 

 [[[ 9 10]
  [11 12]]] 

 [[[13 14]
  [15 16]]]


**Q2. Stack two vertical arrays. Calculate the row wise and column wise sum of the matrix.**

In [23]:
a1 = np.array(list(range(1, 11)))
a2 = np.array(list(range(11, 21)))
a3 = a1.T
a4 = a2.T

a_stacked = np.stack((a3, a4))
a_stacked = a_stacked.T

print("Stacked Array = ")
print(a_stacked)

row_sum = np.empty(10)
column_sum = np.empty(2)

row_sum = np.sum(a_stacked, axis = 1)
column_sum = np.sum(a_stacked, axis = 0)

print("Sum of each row = ", row_sum)
print("Sum of each column = ", column_sum)

Stacked Array = 
[[ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]
 [10 20]]
Sum of each row =  [12 14 16 18 20 22 24 26 28 30]
Sum of each column =  [ 55 155]


**Q3. Create a 3 by 3 array with default value = 7.**

In [25]:
arr7 = np.full((3, 3), 7)
print("Required Array = ")
print(arr7)

Required Array = 
[[7 7 7]
 [7 7 7]
 [7 7 7]]
